server:
  port: ${SERVER_PORT:8081}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  application:
    name: tecrubesi-topic
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres?currentSchema=neutar_topic
    username: postgres
    password: 123456
  flyway:
    enabled: true
    schemas: neutar_topic
  kafka:
    listener:
      missing-topics-fatal: false
kafka:
  bootstrap-servers: ${KAFKA_HOST:localhost}:9092
  groupId: neutar_topic